#!/bin/sh

set -e
set -u

ESC="$(printf '\033')"

if [ "${NOCOLOR+x}" != 'x' ] || [ "${NO_COLOR+x}" != 'x' ]; then
 RED="${ESC}[31m"
 GREEN="${ESC}[32m"
 YELLOW="${ESC}[33m"
 RESET="${ESC}[0m"
else
 RED=''
 GREEN=''
 YELLOW=''
 RESET=''
fi


DEFAULT_URL_BASE='https://get.please.build'

OS="$(uname)"

if [ "${OS}" = 'Darwin' ]; then
 ARCH="$(uname -m)"
else
 ARCH='amd64'
fi

case "${ARCH}" in
 aarch64_be|aarch64|armv8b|armv8l) ARCH='arm64' ;;
 x86_64) ARCH='amd64' ;;
esac

has_command () {
 command -v "${1}" > /dev/null 2>&1
}

get_profile () {
 while [ "${#}" -gt 0 ]
 do
 case "${1}" in
 --profile=*) echo "${1#*=}"; return;;
 --profile) echo "${2}"; return;;
 *) shift;;
 esac
 done
}

PROFILE="${PLZ_CONFIG_PROFILE:-$(get_profile "${@}")}"

CONFIGS="$(cat <<- EOS
	.plzconfig.local
	${PROFILE:+.plzconfig.${PROFILE}}
	.plzconfig_${OS}_${ARCH}
	.plzconfig
	${HOME}/.config/please/plzconfig
	/etc/please/plzconfig
EOS
)"

read_config() {
 set -f

 old_ifs="${IFS}"
 search_term="${1}"

 IFS='
'

 set -- ${CONFIGS}

 grep -i "${search_term}" "${@}" 2> /dev/null | head -n 1

 IFS="${old_ifs}"
 set +f
}

LOCATION="$(read_config '^\s*location' | cut -d '=' -f 2 | tr -d ' ')"

if [ "${LOCATION:+x}" != 'x' ]; then
 if [ "${HOME:+x}" != 'x' ]; then
 printf >&2 '%b$HOME not set, unsure where to find Please.%b\n' "${RED}" "${RESET}"
 exit 1
 fi

 LOCATION="${HOME}/.please"
else
 LOCATION="$(echo "${LOCATION}" | sed "s|~|${HOME}|")"
fi

TARGET="${LOCATION}/please"

if [ -f "${TARGET}" ]; then
 exec "${TARGET}" ${PLZ_ARGS:-} "${@}"
fi

URL_BASE="$(read_config '^\s*downloadlocation' | cut -d '=' -f 2 | tr -d ' ')"

if [ "${URL_BASE:+x}" != 'x' ]; then
 URL_BASE="${DEFAULT_URL_BASE}"
fi

URL_BASE="${URL_BASE%/}"

VERSION="$(read_config '^\s*version[^a-z]')"
VERSION="${VERSION#*=}"
VERSION="$(echo "${VERSION}" | tr -d ' ')"
VERSION="${VERSION#>=}"

if has_command curl; then
 TRANSFER_TOOL='curl'
 TRANSFER_SILENT_OPTS='-fsSL'
 TRANSFER_PROGRESS_OPTS='-fSL'
elif has_command wget; then
 TRANSFER_TOOL='wget'
 TRANSFER_SILENT_OPTS='-qO-'
 TRANSFER_PROGRESS_OPTS='-O-'
else
 printf >&2 '%bUnable to find network operations command%b\n' "${RED}" "${RESET}"
 printf >&2 'Install curl or wget\n'
 exit 1
fi

if [ "${VERSION:+x}" != 'x' ]; then
 printf >&2 "%bCan't determine version, using latest.%b\n" "${YELLOW}" "${RESET}"
 VERSION=$(${TRANSFER_TOOL} ${TRANSFER_SILENT_OPTS} "${URL_BASE}"/latest_version)
fi

if [ "${OS}" = 'Linux' ]; then
 GOOS='linux'
elif [ "${OS}" = 'Darwin' ]; then
 GOOS='darwin'
elif [ "${OS}" = 'FreeBSD' ]; then
 GOOS='freebsd'
else
 printf >&2 '%bUnknown OS %s%b\n' "${RED}" "${OS}" "${RESET}"
 exit 1
fi

PLEASE_URL="${URL_BASE}/${GOOS}_${ARCH}/${VERSION}/please_${VERSION}.tar.xz"
DIR="${LOCATION}/${VERSION}"

if [ ! -d "${DIR}" ]; then
 rm -Rf "${DIR}"
fi

printf >&2 '%bDownloading Please %s to %s...%b\n' "${GREEN}" "${VERSION}" "${DIR}" "${RESET}"
mkdir -p "${DIR}"
${TRANSFER_TOOL} ${TRANSFER_PROGRESS_OPTS} "${PLEASE_URL}" | tar -xJpf- --strip-components=1 -C "${DIR}"
if [ $? -ne 0 ]; then
 printf >&2 '%bFailed to download Please%b\n' "${RED}" "${RESET}"
 exit 1
fi

for x in "${DIR}"/*; do
 ln -sf "${x}" "${LOCATION}"
done

printf >&2 '%bReady, executing plz...%b\n' "${GREEN}" "${RESET}"
exec "${TARGET}" ${PLZ_ARGS:-} "${@}"
